name: WorldFixer
version: "1.5"
api: ["1.0.0"]
main: com.creeperface.nukkitx.worldfixer.WorldFixer
author: CreeperFace
description: "Now you can fix grass and slabs easily and quickly!"

commands:
    wf:
        description: "Main command"
        
permissions:
    wf:
        description: "Permission to do all actions"
        children:
            wf.command:
                description: "Permission to run all commands"
                children:
                    wf.command.fixcolor:
                        description: "allows fix grass color in your world"
                        default: op
                    wf.command.fixslabs:
                        description: "allows fix wooden slabs in your world"
                        default: op
                    wf.command.fixtiles:
                        description: "allows fix broken tiles in your world"
                        default: op
                    wf.command.fix:
                        description: "allows fix whole world"
                        default: op
                    wf.command.wand:
                        description: "allows select an area"
                        default: op
                    wf.command.removeentities:
                        description: "allows select an area"
                        default: op